"""add incident remediations

Revision ID: fdd9fa12c6fa
Revises: 8a9de3bcca58
Create Date: 2026-08-13 15:20:50.171907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd9fa12c6fa'
down_revision: Union[str, Sequence[str], None] = '8a9de3bcca58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_remediations',
    sa.Column('incident_id', sa.String(length=26), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('proposed_yaml', sa.Text(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('rollout_json', sa.Text(), nullable=True),
    sa.Column('verification_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_remediations_incident_id'), 'incident_remediations', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_remediations_incident_id'), table_name='incident_remediations')
    op.drop_table('incident_remediations')
    # ### end Alembic commands ###
