"""
Standard application error codes.
"""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Application error codes."""

    BAD_REQUEST = "BAD_REQUEST"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

    DATABASE_ERROR = "DATABASE_ERROR"

    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"

    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"